config/routes.rb
Blogassociation::Application.routes.draw do
  resources :myblogs do 
    resources :comments, module: :myblogs
  end

  resources :movies do 
    resources :comments, module: :movies
  end

  get "posts/index"
  devise_for :users
   root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/myblog.rb
class Myblog < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
   has_many :blogs   
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


def create
	@comment = @commentable.comments.new(comment_params)
	@comment.user_id = current_user.id
	@comment.save
	respond_to do |format|
    format.html {redirect_to back}
    format.json { render json: @comment }
  end
end 	

 private
    def set_comment
      @comment = @commentable.comments.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body , :user_id)
    end
end

app/controllers/movies/comments_controller.rb
class Movies::CommentsController < ApplicationController
 before_action :set_commentable
	private

	def set_commentable
		@commentable = Movie.find(params[:movie_id])
	end 
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @movies = Movie.all
    respond_with(@movies)
  end

  def show
    respond_with(@movie)
  end

  def new
    @movie = Movie.new
    respond_with(@movie)
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    respond_with(@movie)
  end

  def update
    @movie.update(movie_params)
    respond_with(@movie)
  end

  def destroy
    @movie.destroy
    respond_with(@movie)
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:name)
    end
end

app/controllers/myblogs/comments_controller.rb
class Myblogs::CommentsController < ApplicationController
   before_action :set_commentable
	private

	def set_commentable
		@commentable = Myblog.find(params[:myblog_id])
	end
end

app/controllers/myblogs_controller.rb
class MyblogsController < ApplicationController
  before_action :set_myblog, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @myblogs = Myblog.all
    respond_with(@myblogs)
  end

  def show
    respond_with(@myblog)
  end

  def new
    @myblog = Myblog.new
    respond_with(@myblog)
  end

  def edit
  end

  def create
    @myblog = Myblog.new(myblog_params)
    @myblog.save
    respond_with(@myblog)
  end

  def update
    @myblog.update(myblog_params)
    respond_with(@myblog)
  end

  def destroy
    @myblog.destroy
    respond_with(@myblog)
  end

  private
    def set_myblog
      @myblog = Myblog.find(params[:id])
    end

    def myblog_params
      params.require(:myblog).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movie/comments_helper.rb
module Movie::CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/myblogs/comments_helper.rb
module Myblogs::CommentsHelper
end

app/helpers/myblogs_helper.rb
module MyblogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<% commentable.comments.each do |comment| %>
<%= comment.body %>
<%end%>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |f|  %>
<%= f.text_area :body %>
<%= f.submit "comment" %>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogassociation</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<%= render partial: "comments/comments", locals:{ commentable: @movie}%>

<%= render partial: "comments/form", locals:{ commentable: @movie}%>

app/views/myblogs/_form.html.erb
<%= form_for(@myblog) do |f| %>
  <% if @myblog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myblog.errors.count, "error") %> prohibited this myblog from being saved:</h2>

      <ul>
      <% @myblog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myblogs/edit.html.erb
<h1>Editing myblog</h1>

<%= render 'form' %>

<%= link_to 'Show', @myblog %> |
<%= link_to 'Back', myblogs_path %>

app/views/myblogs/index.html.erb
<h1>Listing myblogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @myblogs.each do |myblog| %>
      <tr>
        <td><%= myblog.name %></td>
        <td><%= link_to 'Show', myblog %></td>
        <td><%= link_to 'Edit', edit_myblog_path(myblog) %></td>
        <td><%= link_to 'Destroy', myblog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Myblog', new_myblog_path %>

app/views/myblogs/new.html.erb
<h1>New myblog</h1>

<%= render 'form' %>

<%= link_to 'Back', myblogs_path %>

app/views/myblogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @myblog.name %>
</p>

<%= render partial: "comments/comments", locals:{ commentable: @myblog}%>

<%= render partial: "comments/form", locals:{ commentable: @myblog}%>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>